controller_list:
  - name: fake_gripping_tool_controller
    joints:
      - wrist
  - name: fake_arm_controller
    joints:
      - hip
      - shoulder
      - elbow
initial:  # Define initial robot poses.
  - group: arm
    pose: strech